---

# Copyright 2020, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Reference:
# https://docs.openstack.org/project-install-guide/dns/ocata/install-ubuntu.html

- name: Creating OpenStack MySQL databases
  mysql_db: name={{ item.db_name }} state=present
  with_items: '{{ mysql_databases }}'

- name: Creating OpenStack MySQL users
  mysql_user:
    host="{{ item.db_host }}"
    name="{{ item.db_user }}"
    password="{{ item.db_pass }}"
    priv="{{ item.db_name }}.*:ALL,GRANT"
    append_privs=true
    state=present
  with_items: '{{ mysql_databases }}'


- include: openstack-designate-init.yml
  when: deployment_mode


- name: Installing Designate
  apt: name={{ item }} state=latest
  with_items:
    - designate
    - designate-worker
    - designate-producer
    - designate-mdns
  notify: restart-designate


- name: Updating designate.conf
  template: src={{ os_release }}/designate.conf.j2
        dest=/etc/designate/designate.conf
        owner=designate
        group=designate
        mode=0640
        backup=yes
  when: item.os_project == "designate"
  with_items: '{{ mysql_databases }}'
  notify: restart-designate


- name: Populating Designate Database
  shell: su -s /bin/sh -c "designate-manage database sync" designate


- name: Updating pools.yaml
  template: src={{ os_release }}/pools.yaml.j2
        dest=/etc/designate/pools.yaml
        owner=designate
        group=designate
        mode=0640
        backup=yes
  when: item.os_project == "designate"
  with_items: '{{ mysql_databases }}'
  notify: restart-designate


- name: Updating Designate Pools Database
  shell: sudo su -s /bin/sh -c "designate-manage pool update" designate


- meta: flush_handlers
