#! /bin/bash

CONTAINER_LIST=`lxc-ls -f | grep vosctrl | grep -v galera | grep -v ceph | awk '{print $1}' | xargs`

for X in $CONTAINER_LIST
do

	echo "Stopping $X..."
        lxc-stop -n $X
	echo

done
