---

- name: main - Fail if users variable not found
  fail:
    msg: "|
        You have to define a users variable. Example:
        users:
          - name: John Doe
            username: jdoe
            key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC...
            "
  when: 'users is undefined'

- name: main - For each user include manage-user.yml
  include: manage-user.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: 'user'

- name: main - For each user include add_user_key.yml
  include: add-user-key.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: 'user'
