---

# Copyright 2020, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: main - Install Bind9 Server
  apt:
    state: present
    name: bind9

- name: main - Bind9 defaults
  copy:
    src: bind9
    dest: /etc/default/bind9
  notify: Restart Bind

- name: main - Configuring RNDC Key
  template:
    src: rndc.key.j2
    dest: /etc/bind/rndc.key
  when: dns_role == "master"
  notify: Restart Bind

- name: main - Configure Bind Options
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options group=bind
  notify: Restart Bind

- name: main - Configure Bind Local
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local group=bind
  notify: Restart Bind


#- name: main - Freeze subnets
#  command: rndc freeze {{ item.key }}
#  with_dict:
#    "{{ subnets }}"

- name: main - Configure subnets
  template: src=subnet.hosts.j2 dest=/var/lib/bind/{{ item.key }}.hosts group=bind mode=0660
  with_dict:
    "{{ subnets }}"
  when: dns_role == "master"
  notify: Restart Bind

- name: main - Configure RDNS for subnets
  template: src=rdns.rev.j2 dest=/var/lib/bind/{{ item.value.reverse }}.rev group=bind mode=0660
  when: item.value.reverse|default(false) and dns_role == "master"
  with_dict:
    "{{ subnets }}"
  notify: Restart Bind

#- name: main - Reload subnets
#  command: rndc reload {{ item.key }}
#  with_dict:
#    "{{ subnets }}"

#- name: main - Unfreeze subnets
#  command: rndc thaw {{ item.key }}
#  with_dict:
#    "{{ subnets }}"

#- name: Ensure /var/lib/bind is owned by Bind
#  file: path=/var/lib/bind owner=bind group=bind recurse=yes state=directory
