---

- name: spin-instance-lxd - Create {{ instance.name }} Instance
  lxd_container:
    name: "{{ instance.name }}"
    state: "{{ instance.state }}"
    source:
      type: image
      mode: pull
      protocol: simplestreams
      # From Canonical
      alias: "{{ instance.distro }}"
      server: https://cloud-images.ubuntu.com/releases
      # From Community
      #server: https://images.linuxcontainers.org
      #alias: "ubuntu/{{ instance.distro }}/cloud"
    config:
      user.user-data: "{{ lookup('template', 'lxd-user-data.j2') }}"
      user.network-config: "{{ lookup('template', 'lxd-network-config.j2') }}"
    profiles: ["{{ instance.profile }}"]
    devices: "{{ instance.devices }}"
    wait_for_ipv4_addresses: false
