---

# Copyright 2020, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Reference:
# https://docs.openstack.org/ceilometer/queens/install/install-base-ubuntu.html

#- name: Creating OpenStack Telemetry Service
#  environment: "{{ admin_openrc_env }}"
#  command: "{{ item }}"
#  with_items:
#  - openstack service create --name ceilometer --description "OpenStack Telemetry Service" metering


# Ceilometer Endpoint is DEPRECATED! Use Gnocchi instead.
#- name: Creating OpenStack Telemetry Endpoint
#  environment: "{{ admin_openrc_env }}"
#  command: "{{ item }}"
#  with_items:
#  - openstack endpoint create --region "{{ region }}" metering public http://{{ os_public_addr }}:8777
#  - openstack endpoint create --region "{{ region }}" metering internal http://{{ os_admin_addr }}:8777
#  - openstack endpoint create --region "{{ region }}" metering admin http://{{ os_admin_addr }}:8777


- name: Creating OpenStack Telemetry User and Role
  environment: "{{ admin_openrc_env }}"
  command: "{{ item }}"
  with_items:
  - openstack user create --domain default --password "{{ service_password }}" --email "ceilometer@{{ os_dns_domain }}" ceilometer
  - openstack role add --project service --user ceilometer --user-domain default admin
