---

#
# Top Level Playbook for Bare Infrastructure
#

- hosts: all
  become: yes
  roles:
  - bootstrap


- hosts: metais
  become: yes
  roles:
  - ansible
  - ssh_keypair


- hosts: all
  become: yes
  roles:
  - post-cleanup
