---

#
# Top Level Playbook for Bare Infrastructure
#

- hosts: all
  become: yes
  roles:
  - bootstrap
  - grub
  - time


- hosts: metais
  become: yes
  roles:
  - ansible
  - ssh_keypair
  - packer


- hosts: all
  become: yes
  roles:
  - post-cleanup
