---
# Copyright 2018, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
  

# Set default as the VM exists
- name: set_fact vm_exists
  set_fact:
    vm_exists: True

# Check VM status
- name: check vm status ({{ vm.name }})
  block:
  - virt:
      name: "{{ vm.name }}"
      command: status
    register: vm_status_msg
    failed_when: vm_status_msg == 0
  rescue:
  - debug:
      msg: "Error checking {{ vm.name }} status!"

#- name: fail when python-libvirt module is not importable
#  fail:
#    msg: "Package python-libvirt not found."
#  when: "vm_status_msg.msg == 'The `python-libvirt` module is not importable. Check the requirements.'"

# Create static virtual machine not found message
- name: create vm_not_found fact ({{ vm.name }})
  set_fact:
    vm_not_found: "virtual machine {{ vm.name }} not found"

# Set vm_exists to false based on the vm status error message
- name: set_fact vm_exists (with status verified) ({{ vm.name }})
  set_fact:
    vm_exists: False
  when:
    - vm_status_msg.msg is defined
    - vm_status_msg.msg == vm_not_found
