---

# This role installs and sets up keepalived

- name: main - Yum Install keepalived
  yum: name=keepalived state=present
  when: ansible_distribution == "CentOS"
  tags: keepalived
  notify: restart keepalived

- name: main - Apt Install keepalived
  apt: name=keepalived state=latest
  when: ansible_distribution == "Ubuntu"
  tags: keepalived
  notify: restart keepalived

- name: main - chk_service script shell
  template: 
    src: check_script.sh.j2 
    dest: /etc/keepalived/check_script.sh
    mode: 0755
    owner: root
    group: root
  tags: keepalived
  when: ka_profile == "dhcp"
  notify: restart keepalived

- name: main - Config keepalived
  template: src=keepalived_conf_{{ ka_profile }}.j2 dest=/etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: main - Start keepalived
  service: name=keepalived state=started
  tags: keepalived
