---

# Copyright 2020, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#
# Linux Flavors - Generic
#

#- name: main - nova creating m1.micro flavor
#  environment: "{{admin_openrc_env}}"
#  os_nova_flavor:
#    validate_certs: false
#    state: present
#    name: m1.micro
#    ram: 256
#    vcpus: 1
#    disk: 4

#- name: main - nova creating m1.tiny flavor
#  environment: "{{admin_openrc_env}}"
#  os_nova_flavor:
#    validate_certs: false
#    state: present
#    name: m1.tiny
#    ram: 512
#    vcpus: 1
#    disk: 8

- name: main - nova creating m1.little flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: m1.little
    ram: 1024
    vcpus: 1
    disk: 8

- name: main - nova creating m1.small flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: m1.small
    ram: 2048
    vcpus: 2
    disk: 16

- name: main - nova creating m1.medium flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: m1.medium
    ram: 4096
    vcpus: 4
    disk: 32

- name: main - nova creating m1.large flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: m1.large
    ram: 8192
    vcpus: 8
    disk: 64

- name: main - nova creating m1.xlarge flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: m1.xlarge
    ram: 16384
    vcpus: 16
    disk: 128


#
# Linux Flavors - CPU Intensive
#

- name: main - nova creating c1.little flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: c1.little
    ram: 1024
    vcpus: 2
    disk: 8

- name: main - nova creating c1.small flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: c1.small
    ram: 2048
    vcpus: 4
    disk: 16

- name: main - nova creating c1.medium flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: c1.medium
    ram: 4096
    vcpus: 8
    disk: 32

- name: main - nova creating c1.large flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: c1.large
    ram: 8192
    vcpus: 16
    disk: 64

- name: main - nova creating c1.xlarge flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: c1.xlarge
    ram: 16384
    vcpus: 32
    disk: 128


#
# Linux Flavors - RAM Intensive
#

- name: main - nova creating r1.little flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: r1.little
    ram: 2048
    vcpus: 1
    disk: 8

- name: main - nova creating r1.small flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: r1.small
    ram: 4096
    vcpus: 2
    disk: 16

- name: main - nova creating r1.medium flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: r1.medium
    ram: 8192
    vcpus: 4
    disk: 32

- name: main - nova creating r1.large flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: r1.large
    ram: 16384
    vcpus: 8
    disk: 64

- name: main - nova creating r1.xlarge flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: r1.xlarge
    ram: 32768
    vcpus: 16
    disk: 128


#
# Linux Flavors - Storage Intensive
#

- name: main - nova creating s1.little flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: s1.little
    ram: 1024
    vcpus: 1
    disk: 32

- name: main - nova creating s1.small flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: s1.small
    ram: 2048
    vcpus: 2
    disk: 64

- name: main - nova creating s1.medium flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: s1.medium
    ram: 4096
    vcpus: 4
    disk: 128

- name: main - nova creating s1.large flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: s1.large
    ram: 8192
    vcpus: 8
    disk: 256

- name: main - nova creating s1.xlarge flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: s1.xlarge
    ram: 16384
    vcpus: 16
    disk: 512


#
# Windows Flavors
#

- name: main - nova creating w1.little flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: w1.little
    ram: 2048
    vcpus: 2
    disk: 48

- name: main - nova creating w1.small flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: w1.small
    ram: 4096
    vcpus: 4
    disk: 64

- name: main - nova creating w1.medium flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: w1.medium
    ram: 8192
    vcpus: 8
    disk: 96

- name: main - nova creating w1.large flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: w1.large
    ram: 16384
    vcpus: 16
    disk: 128

- name: main - nova creating w1.xlarge flavor
  environment: "{{admin_openrc_env}}"
  os_nova_flavor:
    validate_certs: false
    state: present
    name: w1.xlarge
    ram: 32768
    vcpus: 32
    disk: 256
